from pydantic import BaseModel

class MessageRequest(BaseModel):
    """
    Model representing the incoming message request from the user.

    Attributes:
        message (str): The message sent by the user to the bot.
    """
    message: str

class MessageResponse(BaseModel):
    """
    Model representing the response message from the bot.

    Attributes:
        response (str): The response generated by the bot based on the user's message.
    """
    response: str
