import logging
from .agents.manager import manager, info, inventory, finance


# Configure logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def bot_response(message: str) -> str:
    """
    Generate a response from the bot based on the user's message.

    Args:
        message (str): The message from the user to be processed.

    Returns:
        str: The response generated by the bot based on the user's intention.
    
    Logs:
        Logs the intention detected and the chosen response type for debugging and monitoring purposes.
    """
    try:
        # Determine the user's intention
        intention = manager(message)
        logger.info(f"Detected user intention: {intention}")

        # Generate response based on intention
        if intention == "info":
            response = info(message)
        elif intention == "inventory":
            response = inventory(message)
        elif intention == "finance":
            response = finance(message)
        else:
            logger.warning(f"Unrecognized intention '{intention}', defaulting to 'info'")
            response = info(message)

        return response
    except Exception as e:
        logger.error(f"Error generating bot response: {e}")
        return "Sorry, there was an error processing your request."
    